INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("ADF", "Andorran Franc", "7.4659", "7.4659", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("ADP", "Andorran Peseta", "186.167", "186.167", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("AED", "Utd. Arab Emir. Dirham", "3.6735", "3.6735", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("AFN", "Afghanistan Afghani", "49.59", "49.59", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("ALL", "Albanian Lek", "83.522", "83.522", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("AMD", "Armenian Dram", "308.69", "308.69", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("ANG", "NL Antillian Guilder", "1.8", "1.8", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("AOA", "Angolan Kwanza", "75.158", "75.158", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("AON", "Angolan New Kwanza", "75.158", "75.158", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("ARS", "Argentine Peso", "3.1547", "3.1547", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("ATS", "Austrian Schilling", "0.6532", "0.6532", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("AUD", "Australian Dollar", "1.0709", "1.0709", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("AWG", "Aruban Florin", "1.8", "1.8", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("AZM", "Azerbaijan Manat", "4214.5", "4214.5", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("AZN", "Azerbaijan New Manat", "0.8429", "0.8429", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("BAM", "Bosnian Mark", "1.2757", "1.2757", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("BBD", "Barbados Dollar", "2.02", "2.02", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("BDT", "Bangladeshi Taka", "69.559", "69.559", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("BEF", "Belgian Franc", "0.6532", "0.6532", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("BGN", "Bulgarian Lev", "1.276", "1.276", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("BHD", "Bahraini Dinar", "0.3786", "0.3786", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("BIF", "Burundi Franc", "1187.8", "1187.8", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("BMD", "Bermudian Dollar", "0.9952", "0.9952", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("BND", "Brunei Dollar", "1.3978", "1.3978", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("BOB", "Bolivian Boliviano", "7.6606", "7.6606", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("BRL", "Brazilian Real", "1.6681", "1.6681", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("BSD", "Bahamian Dollar", "1.0178", "1.0178", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("BTN", "Bhutan Ngultrum", "40.32", "40.32", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("BWP", "Botswana Pula", "6.6151", "6.6151", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("BYR", "Belarusian Ruble", "2151.5", "2151.5", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("BZD", "Belize Dollar", "2.0018", "2.0018", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("CAD", "Canadian Dollar", "0.9856", "0.9856", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("CDF", "Congolese Franc", "437", "437", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("CHF", "Swiss Franc", "1.0333", "1.0333", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("CLP", "Chilean Peso", "446.65", "446.65", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("CNY", "Chinese Yuan Renminbi", "7.1172", "7.1172", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("COP", "Colombian Peso", "1891.5", "1891.5", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("CRC", "Costa Rican Colon", "505.08", "505.08", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("CUC", "Cuban Convertible Peso", "0.9259", "0.9259", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("CUP", "Cuban Peso", "23.1481", "23.1481", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("CVE", "Cape Verde Escudo", "75.809", "75.809", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("CYP", "Cyprus Pound", "0.6532", "0.6532", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("CZK", "Czech Koruna", "16.3688", "16.3688", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("DEM", "German Mark", "0.6532", "0.6532", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("DJF", "Djibouti Franc", "178.61", "178.61", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("DKK", "Danish Krone", "4.8604", "4.8604", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("DOP", "Dominican R. Peso", "34.473", "34.473", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("DZD", "Algerian Dinar", "65.954", "65.954", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("ECS", "Ecuador Sucre", "25587", "25587", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("EEK", "Estonian Kroon", "10.2075", "10.2075", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("EGP", "Egyptian Pound", "5.5073", "5.5073", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("ESP", "Spanish Peseta", "0.6532", "0.6532", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("ETB", "Ethiopian Birr", "9.4639", "9.4639", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("EUR", "Euro", "0.6532", "0.6532", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("FIM", "Finnish Markka", "0.6532", "0.6532", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("FJD", "Fiji Dollar", "1.4955", "1.4955", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("FKP", "Falkland Islands Pound", "0.5001", "0.5001", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("FRF", "French Franc", "0.6532", "0.6532", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("GBP", "British Pound", "0.5008", "0.5008", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("GEL", "Georgian Lari", "1.766", "1.766", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("GHC", "Ghanaian Cedi", "10099", "10099", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("GHS", "Ghanaian New Cedi", "1.0099", "1.0099", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("GIP", "Gibraltar Pound", "0.5001", "0.5001", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("GMD", "Gambian Dalasi", "22.422", "22.422", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("GNF", "Guinea Franc", "4429.1", "4429.1", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("GRD", "Greek Drachma", "0.6532", "0.6532", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("GTQ", "Guatemalan Quetzal", "7.8023", "7.8023", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("GYD", "Guyanese Dollar", "203.67", "203.67", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("HKD", "Hong Kong Dollar", "7.7881", "7.7881", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("HNL", "Honduran Lempira", "19.477", "19.477", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("HRK", "Croatian Kuna", "4.75", "4.75", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("HTG", "Haitian Gourde", "38.154", "38.154", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("HUF", "Hungarian Forint", "172.07", "172.07", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("IDR", "Indonesian Rupiah", "9032", "9032", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("IEP", "Irish Punt", "0.6532", "0.6532", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("ILS", "Israeli New Shekel", "3.6002", "3.6002", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("INR", "Indian Rupee", "40.32", "40.32", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("IQD", "Iraqi Dinar", "1228.6", "1228.6", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("IRR", "Iranian Rial", "9406.1", "9406.1", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("ISK", "Iceland Krona", "66.4285", "66.4285", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("ITL", "Italian Lira", "0.6532", "0.6532", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("JMD", "Jamaican Dollar", "71.2", "71.2", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("JOD", "Jordanian Dinar", "0.7135", "0.7135", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("JPY", "Japanese Yen", "103.564", "103.564", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("KES", "Kenyan Shilling", "67.8128", "67.8128", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("KGS", "Kyrgyzstanian Som", "36.3863", "36.3863", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("KHR", "Cambodian Riel", "4015.3", "4015.3", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("KMF", "Comoros Franc", "323", "323", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("KPW", "North Korean Won", "140", "140", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("KRW", "South-Korean Won", "949.27", "949.27", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("KWD", "Kuwaiti Dinar", "0.2733", "0.2733", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("KYD", "Cayman Islands Dollar", "0.8333", "0.8333", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("KZT", "Kazakhstan Tenge", "122.67", "122.67", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("LAK", "Lao Kip", "8992.2", "8992.2", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("LBP", "Lebanese Pound", "1533.6", "1533.6", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("LKR", "Sri Lanka Rupee", "107.935", "107.935", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("LRD", "Liberian Dollar", "62.5", "62.5", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("LSL", "Lesotho Loti", "7.8525", "7.8525", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("LTL", "Lithuanian Litas", "2.2516", "2.2516", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("LUF", "Luxembourg Franc", "0.6532", "0.6532", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("LVL", "Latvian Lats", "0.4554", "0.4554", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("LYD", "Libyan Dinar", "1.2297", "1.2297", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("MAD", "Moroccan Dirham", "7.5171", "7.5171", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("MDL", "Moldovan Leu", "11.166", "11.166", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("MGA", "Malagasy Ariary", "1817.7", "1817.7", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("MGF", "Malagasy Franc", "9150.46", "9150.46", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("MKD", "Macedonian Denar", "40.6206", "40.6206", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("MMK", "Myanmar Kyat", "6.5559", "6.5559", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("MNT", "Mongolian Tugrik", "1172.31", "1172.31", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("MOP", "Macau Pataca", "8.1521", "8.1521", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("MRO", "Mauritanian Ouguiya", "256.57", "256.57", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("MTL", "Maltese Lira", "0.6532", "0.6532", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("MUR", "Mauritius Rupee", "27.5783", "27.5783", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("MVR", "Maldive Rufiyaa", "12.96", "12.96", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("MWK", "Malawi Kwacha", "142.751", "142.751", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("MXN", "Mexican Peso", "10.7227", "10.7227", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("MYR", "Malaysian Ringgit", "3.1697", "3.1697", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("MZM", "Mozambique Metical", "24210", "24210", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("MZN", "Mozambique New Metical", "24.21", "24.21", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("NAD", "Namibia Dollar", "7.9137", "7.9137", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("NGN", "Nigerian Naira", "117.932", "117.932", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("NIO", "Nicaraguan Cordoba Oro", "19.397", "19.397", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("NLG", "Dutch Guilder", "0.6532", "0.6532", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("NOK", "Norwegian Kroner", "5.1258", "5.1258", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("NPR", "Nepalese Rupee", "65.48", "65.48", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("NZD", "New Zealand Dollar", "1.2473", "1.2473", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("OMR", "Omani Rial", "0.3863", "0.3863", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("PAB", "Panamanian Balboa", "1.0165", "1.0165", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("PEN", "Peruvian Nuevo Sol", "2.9247", "2.9247", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("PGK", "Papua New Guinea Kina", "2.804", "2.804", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("PHP", "Philippine Peso", "40.5978", "40.5978", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("PKR", "Pakistan Rupee", "63.1499", "63.1499", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("PLN", "Polish Zloty", "2.3139", "2.3139", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("PTE", "Portuguese Escudo", "0.6532", "0.6532", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("PYG", "Paraguay Guarani", "4654.9", "4654.9", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("QAR", "Qatari Rial", "3.6386", "3.6386", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("ROL", "Romanian Lei", "24202.8", "24202.8", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("RON", "Romanian New Lei", "2.4203", "2.4203", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("RSD", "Serbian Dinar", "54.8951", "54.8951", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("RUB", "Russian Rouble", "23.8893", "23.8893", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("RWF", "Rwandan Franc", "554.19", "554.19", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("SAR", "Saudi Riyal", "3.7524", "3.7524", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("SBD", "Solomon Islands Dollar", "7.6336", "7.6336", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("SCR", "Seychelles Rupee", "8.0848", "8.0848", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("SDD", "Sudanese Dinar", "204.528", "204.528", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("SDG", "Sudanese Pound", "2.0453", "2.0453", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("SDP", "Sudanese Old Pound", "2272.3", "2272.3", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("SEK", "Swedish Krona", "6.1088", "6.1088", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("SGD", "Singapore Dollar", "1.3874", "1.3874", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("SHP", "St. Helena Pound", "0.5737", "0.5737", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("SIT", "Slovenian Tolar", "0.6532", "0.6532", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("SKK", "Slovak Koruna", "21.2841", "21.2841", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("SLL", "Sierra Leone Leone", "3002.87", "3002.87", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("SOS", "Somali Shilling", "1424.1", "1424.1", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("SRD", "Suriname Dollar", "2.78", "2.78", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("SRG", "Suriname Guilder", "2780", "2780", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("STD", "Sao Tome/Principe Dobra", "14710", "14710", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("SVC", "El Salvador Colon", "8.909", "8.909", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("SYP", "Syrian Pound", "52.013", "52.013", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("SZL", "Swaziland Lilangeni", "7.731", "7.731", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("THB", "Thai Baht", "31.8126", "31.8126", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("TMM", "Turkmenistan Manat", "5200.1", "5200.1", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("TND", "Tunisian Dinar", "1.1994", "1.1994", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("TOP", "Tonga Paanga", "2.0747", "2.0747", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("TRL", "Turkish Lira", "1224080", "1224080", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("TRY", "Turkish New Lira", "1.2241", "1.2241", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("TTD", "Trinidad/Tobago Dollar", "6.351", "6.351", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("TWD", "Taiwan Dollar", "30.689", "30.689", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("TZS", "Tanzanian Shilling", "1189.85", "1189.85", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("UAH", "Ukraine Hryvnia", "5.1329", "5.1329", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("UGX", "Uganda Shilling", "1721", "1721", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("USD", "United States Dollar", "1", "1", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("UYU", "Uruguayan Peso", "21.241", "21.241", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("VEB", "Venezuelan Bolivar", "2152.41", "2152.41", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("VEF", "Venezuelan Bolivar Fuerte", "2.1524", "2.1524", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("VND", "Vietnamese Dong", "16179", "16179", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("VUV", "Vanuatu Vatu", "97.5", "97.5", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("WST", "Samoan Tala", "2.4869", "2.4869", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("XAF", "CFA Franc BEAC", "436.6", "436.6", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("XAG", "Silver (oz.)", "0.0495", "0.0495", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("XAU", "Gold (oz.)", "0.001024", "0.001024", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("XCD", "East Caribbean Dollar", "2.725", "2.725", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("XEU", "ECU", "0.6532", "0.6532", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("XOF", "CFA Franc BCEAO", "436.64", "436.64", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("XPD", "Palladium (oz.)", "0.001976", "0.001976", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("XPF", "CFP Franc", "79.402", "79.402", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("XPT", "Platinum (oz.)", "0.0004625", "0.0004625", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("YER", "Yemeni Rial", "199.25", "199.25", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("YUN", "Yugoslav Dinar", "54.8951", "54.8951", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("ZAR", "South African Rand", "7.8105", "7.8105", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("ZMK", "Zambian Kwacha", "3790.4", "3790.4", "USD", now(), now());
INSERT INTO currency (iso_code, name, current_rate, previous_rate, base_currency, created_at, updated_at) VALUES ("ZWD", "Zimbabwe Dollar", "30654", "30654", "USD", now(), now());
